### PR TITLE
First set of changes

### PR DESCRIPTION
**Pull request by dill**
Thanks for sending this through Eric. A couple of quick thoughts that we can chat about next week (Tuesday morning?).

I've forked the project and altered the poster:

- there's a lot of text, I've tried to cut some of this
- I think the diagram of the output from`convert_project` probably isn't right for the poster and I think to do it justice, it probably requires more information on each of it's components, this might be better in another venue, the immediately useful info is already in that box 
- cleared up use of `mrds` vs. `ddf()` etc
- simplified the R code for presentation, change focus of this box to show what is in the objects
- removed figure captions
- removed highlighting from test results table
- changed "bridging..." to be more about distance file format and what we do to get data out

I've tried to keep commits separate, so you can reject things if you like.

I'll try to make some more edits before Tuesday (assuming that's when we'll meet).

For the references, I think it's easier to have the bibliography only have the JAE paper and a link to the bioRxiv paper, then just say the package names are on CRAN?

### CODE REVIEW

**Comment by erex** [comment]
I'm away today (Sunday), will rummage through your revisions on Monday.  Tuesday morning (1000?) would be good for me to discuss this.

**Comment by dill** [comment]
In my diary.

**Comment by erex** [comment]
regarding bibliography, readdst is not on CRAN.  Will it be prior to ISEC?  If not, then perhaps it should remain in bibliography

**Comment by dill** [comment]
Folks looking at the poster will simply want to know where to download things from. Don’t think a bib entry helps with that. 

Suggest we say that they should consult distancesampling.org/R ? That way they have an easy to remember URL?

**Pull request merged**
